### ISSUE TITLE
Display some form of alert for charts that haven't received data in some time

### ISSUE THREAD

**Issue by marianamarasoiu** [AfricasVoices/nook_watcher#12]
This may be an indication of a problem in the pipelines, so the alert should make the charts stand out a lot, e.g. the background should turn red.

Let's use 1h as the gap period length for now.

**Comment by ktkization** [comment]
Picking this up

**Comment by ktkization** [comment]
Here is the [PL](https://github.com/AfricasVoices/nook_watcher/pull/26)

**Comment by ktkization** [comment]
### Test Cases
#### Test Case 1
When new data is received:

1. When project data for the selected project is not null and is stale then its project timer is set to null.
2. When project data for the selected project is not null and is not stale then a new project timer is created.
3. When project data for the selected project is not null then it's timer is cancelled before a new project timer is set. 
4. When the selected project timer is null and the selected project timer is not active then the charts are marked as stale otherwise they're marked as not stale.
5. When the selected project timer runs out and executes then the charts are marked as stale

#### Test Case 2
When a project is selected from the dropdown list:

1. When the selected project timer is null and the selected project timer is not active then the charts are marked as stale otherwise they're marked as not stale.

**Comment by ktkization** [comment]
@marianamarasoiu You can add what I might have forgotten in the test cases above
